spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.129.0.76:3306/nutriguide?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: nutriguide
    password: 200173lol@...
    
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.example.nutri_guide_background.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-prefix: ""
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

jwt:
  secret: your_jwt_secret
  expiration: 86400000
